# Generated by Django 4.2 on 2024-02-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcotegory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
    ]
